apiVersion: networking.k8s.io/v1 
kind: Ingress 
metadata: 
  name: podinfo 
  namespace: kedademo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec: 
  ingressClassName: nginx
  rules:     
    - host: kedademo.seanmck.dev
      http: 
        paths: 
          - backend: 
              service: 
                name: podinfo 
                port: 
                  number: 80 
            path: / 
            pathType: Prefix 